=== adenskevitch/new-wear-shop/src/main/resources/buyerData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="shop" type="byersType"/>

    <xs:simpleType name="paramType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="paramValueType">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="moneyType">
        <xs:restriction base="xs:float"/>
    </xs:simpleType>

    <xs:complexType name="sizeType">
        <xs:sequence>
            <xs:element type="paramType" name="key"/>
            <xs:element type="paramValueType" name="value"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sizesType">
        <xs:sequence minOccurs="3" maxOccurs="3">
            <xs:element type="sizeType" name="entry"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="birthdayType">
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>

    <xs:simpleType name="todayType">
        <xs:restriction base="xs:date"/>
    </xs:simpleType>

    <xs:complexType name="buyerType">
        <xs:sequence>
            <xs:element type="birthdayType" name="birthday"/>
            <xs:element type="moneyType" name="money"/>
            <xs:element type="sizesType" name="sizes"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="firstName"/>
    </xs:complexType>

    <xs:complexType name="byersType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element type="todayType" name="today"/>
            <xs:element type="buyerType" name="buyer" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== adenskevitch/new-wear-shop/src/main/resources/buyerData.xml
<?xml version="1.0" encoding="UTF-8"?>
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/new/java/new-wear-shop/src/main/resources/buyerData.xsd">
    <buyer firstName="Ivan">
        <money>600.00</money>
        <sizes>
            <entry>
                <key>height</key>
                <value>170</value>
            </entry>
            <entry>
                <key>chest</key>
                <value>80</value>
            </entry>
            <entry>
                <key>waist</key>
                <value>50</value>
            </entry>
        </sizes>
    </buyer>
    <buyer firstName="Vladimir">
        <money>800.00</money>
        <sizes>
            <entry>
                <key>height</key>
                <value>180</value>
            </entry>
            <entry>
                <key>chest</key>
                <value>85</value>
            </entry>
            <entry>
                <key>waist</key>
                <value>55</value>
            </entry>
        </sizes>
    </buyer>
</shop>
